<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LENS & LIGHT — Fotographer</title>
    <meta name="description" content="LENS & LIGHT — cinematic photography for life's most meaningful frames.">
    <link rel="preconnect" href="https://images.unsplash.com">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Playfair+Display:ital,wght@0,500;0,600;1,500&display=swap');
        :root{--paper:#faf9f6;--ink:#1a1a1a;--soft:#77736d;--taupe:#d4c5b9;--line:#dedbd5;--serif:'Playfair Display',Georgia,serif;--sans:'DM Sans',sans-serif}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:14px}a{color:inherit;text-decoration:none}button{font:inherit;cursor:pointer} .shell{width:min(1280px,calc(100% - 64px));margin:auto}
        .nav{height:86px;display:flex;align-items:center;justify-content:space-between;position:absolute;top:0;left:0;right:0;z-index:5}.brand{font:600 17px var(--serif);letter-spacing:.02em}.brand small{font:10px var(--sans);letter-spacing:.2em;text-transform:uppercase;margin-left:8px;color:var(--soft)}.navlinks{display:flex;align-items:center;gap:28px;font-size:12px;letter-spacing:.05em;text-transform:uppercase}.navlinks a{color:#595650}.navlinks a:hover{color:#000}.navlinks .pill{border:1px solid var(--ink);padding:10px 16px;border-radius:99px;color:var(--ink)}
        .hero{min-height:780px;display:grid;grid-template-columns:45% 55%;align-items:center;padding-top:82px;position:relative;overflow:hidden}.hero-copy{padding:50px 8% 50px 0}.eyebrow{font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:var(--soft);margin-bottom:24px}.hero h1{font:500 clamp(56px,7.5vw,112px)/.91 var(--serif);letter-spacing:-.075em;margin:0;max-width:610px}.hero h1 em{font-style:italic;color:#8f7768}.hero-intro{max-width:355px;color:var(--soft);line-height:1.75;margin:29px 0 30px}.button{display:inline-flex;align-items:center;gap:16px;background:var(--ink);color:#fff;border-radius:99px;padding:14px 19px;font-size:11px;text-transform:uppercase;letter-spacing:.1em;transition:transform .25s,background .25s}.button:hover{transform:translateY(-3px);background:#5a4b42}.hero-meta{display:flex;gap:24px;margin-top:73px;color:var(--soft);font-size:11px}.hero-meta strong{display:block;color:var(--ink);font:500 27px var(--serif);margin-bottom:4px}.hero-art{height:650px;position:relative;display:grid;place-items:center}.hero-art:after{content:"";position:absolute;width:440px;height:80px;background:#baa99b;opacity:.2;filter:blur(32px);bottom:70px;border-radius:50%}.portrait{width:62%;height:76%;object-fit:cover;filter:saturate(.8);position:relative;z-index:1}.hero-frame{position:absolute;width:59%;height:74%;border:1px solid var(--taupe);transform:translate(25px,-17px);z-index:0}.hero-side{position:absolute;right:5%;bottom:92px;writing-mode:vertical-rl;text-transform:uppercase;letter-spacing:.2em;font-size:9px;color:var(--soft)}.scrollmark{position:absolute;bottom:25px;left:0;font-size:10px;text-transform:uppercase;letter-spacing:.17em;color:var(--soft)}
        .section{padding:125px 0}.section-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:45px}.kicker{font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:var(--soft);margin-bottom:16px}.section h2{font:500 clamp(39px,5vw,67px)/.95 var(--serif);letter-spacing:-.06em;margin:0}.section h2 em{font-style:italic;color:#8f7768}.section-intro{color:var(--soft);line-height:1.7;max-width:280px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:28px}.filter{background:transparent;border:1px solid var(--line);border-radius:99px;padding:9px 14px;font-size:11px;color:var(--soft)}.filter.active,.filter:hover{background:var(--ink);border-color:var(--ink);color:#fff}.gallery{columns:3 260px;column-gap:18px}.gallery-item{break-inside:avoid;margin:0 0 18px;position:relative;overflow:hidden;background:#eee;cursor:none}.gallery-item img{display:block;width:100%;height:auto;transition:transform .7s cubic-bezier(.2,.7,.2,1),filter .5s}.gallery-item:hover img{transform:scale(1.045);filter:brightness(.78)}.gallery-item figcaption{position:absolute;left:18px;bottom:17px;right:18px;color:#fff;opacity:0;transform:translateY(8px);transition:.35s}.gallery-item:hover figcaption{opacity:1;transform:none}.gallery-item figcaption b{font:18px var(--serif);display:block}.gallery-item figcaption span{font-size:10px;text-transform:uppercase;letter-spacing:.12em}.cursor{position:fixed;z-index:20;pointer-events:none;width:20px;height:20px;border:1px solid #fff;border-radius:50%;mix-blend-mode:difference;transform:translate(-50%,-50%) scale(0);transition:transform .2s}.cursor.show{transform:translate(-50%,-50%) scale(1)}
        .about{background:#eee9e3}.about-grid{display:grid;grid-template-columns:1fr 1fr;gap:10%;align-items:center}.about-photo{width:80%;height:540px;object-fit:cover;margin-left:10%}.about-copy p{font:26px/1.35 var(--serif);max-width:480px}.about-copy .body{font:14px/1.8 var(--sans);color:var(--soft);max-width:390px}.signature{font:italic 27px var(--serif);margin-top:32px}
        .services{display:grid;grid-template-columns:35% 1fr;gap:12%}.service-list{border-top:1px solid var(--line)}.service{border-bottom:1px solid var(--line)}.service-toggle{width:100%;border:0;background:none;padding:22px 0;display:flex;justify-content:space-between;text-align:left;font:20px var(--serif)}.service-toggle span{font:22px var(--sans);font-weight:300}.service-detail{max-height:0;overflow:hidden;color:var(--soft);line-height:1.7;transition:max-height .35s}.service.open .service-detail{max-height:120px;padding:0 40px 23px 0}.service.open .service-toggle span{transform:rotate(45deg)}
        .contact{background:#1a1a1a;color:#fff}.contact .kicker,.contact .section-intro{color:#aaa49e}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:12%;align-items:end}.contact h2{font-size:clamp(48px,6vw,90px)}.contact h2 em{color:#d4c5b9}.contact-form{display:grid;gap:18px}.contact-form input,.contact-form textarea{width:100%;background:transparent;border:0;border-bottom:1px solid #555;color:#fff;padding:13px 0;outline:0}.contact-form textarea{min-height:80px;resize:vertical}.contact-form .button{background:#f7f3ed;color:#1a1a1a;border:0;justify-self:start;margin-top:8px}.footer{padding:28px 0;display:flex;justify-content:space-between;color:var(--soft);font-size:11px;border-top:1px solid #3d3d3d}.lightbox{position:fixed;inset:0;background:#111e;backdrop-filter:blur(10px);z-index:15;display:none;place-items:center;padding:35px}.lightbox.open{display:grid}.lightbox img{max-width:min(90vw,1000px);max-height:82vh;object-fit:contain}.lightbox-close,.lightbox-prev,.lightbox-next{position:fixed;border:0;background:none;color:#fff;font-size:28px}.lightbox-close{right:25px;top:18px}.lightbox-prev{left:25px}.lightbox-next{right:25px}.lightbox-label{position:fixed;bottom:21px;left:50%;transform:translateX(-50%);color:#fff;font:18px var(--serif)}
        @media(max-width:800px){.shell{width:calc(100% - 36px)}.navlinks a:not(.pill){display:none}.hero{display:block;min-height:auto;padding-top:125px}.hero-copy{padding:25px 0 15px}.hero h1{font-size:62px}.hero-meta{margin-top:48px}.hero-art{height:480px;margin-top:10px}.portrait{width:70%;height:77%}.hero-frame{width:67%;height:75%}.section{padding:82px 0}.section-head,.contact-grid{display:block}.section-intro{margin-top:22px}.gallery{columns:2 145px;column-gap:10px}.gallery-item{margin-bottom:10px}.about-grid,.services{grid-template-columns:1fr;gap:45px}.about-photo{width:88%;height:420px;margin:0 0 0 6%}.contact-form{margin-top:45px}.footer{display:block}.footer span{display:block;margin-top:10px}}
        @media(prefers-color-scheme:dark){body{--paper:#11100f;--ink:#f4f0e9;--soft:#aaa39b;--line:#393633;--taupe:#72645c}.about{background:#1d1b19}.hero-art:after{opacity:.5}.navlinks a{color:#b6b1a9}.navlinks .pill{border-color:#f4f0e9}.hero-meta strong{color:#f4f0e9}.contact{background:#050505}}
        html[data-fotographer-theme="light"] body{--paper:#faf9f6;--ink:#1a1a1a;--soft:#77736d;--line:#dedbd5;--taupe:#d4c5b9}html[data-fotographer-theme="light"] .about{background:#eee9e3}
        html[data-fotographer-theme="dark"] body{--paper:#11100f;--ink:#f4f0e9;--soft:#aaa39b;--line:#393633;--taupe:#72645c}html[data-fotographer-theme="dark"] .about{background:#1d1b19}html[data-fotographer-theme="dark"] .contact{background:#050505}
        .theme-picker{position:fixed;z-index:12;bottom:18px;left:18px;font-size:11px}.theme-picker button{border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:99px;padding:9px 12px}.theme-menu{display:none;position:absolute;bottom:43px;left:0;background:var(--paper);border:1px solid var(--line);padding:5px;border-radius:10px;box-shadow:0 8px 22px #0002}.theme-picker.open .theme-menu{display:grid;gap:3px}.theme-menu button{border:0;border-radius:6px;text-align:left;white-space:nowrap}.theme-menu button:hover{background:var(--ink);color:var(--paper)}
    </style>
</head>
<body>
<div class="cursor" id="cursor"> </div>
<header class="nav shell"><a class="brand" href="{{ url('/') }}">LENS & LIGHT <small>fotographer</small></a><nav class="navlinks"><a href="{{ route('dashboard') }}">Dashboard</a><a href="{{ route('bookings.calendar') }}">Calendar</a><a href="{{ route('bookings.index') }}">Booking List</a><a class="pill" href="{{ route('bookings.create') }}">New Booking ↗</a></nav></header>
<main>
<section class="hero shell"><div class="hero-copy"><div class="eyebrow">Independent photography studio · Kuala Lumpur</div><h1>Stories worth <em>feeling.</em></h1><p class="hero-intro">We make photographs with a pulse — honest, intimate and made to outlive the moment.</p><a class="button" href="#work">Explore the work <span>↓</span></a><div class="hero-meta"><div><strong>12</strong>years in frame</div><div><strong>240+</strong>stories told</div><div><strong>4.9</strong>client love</div></div></div><div class="hero-art"><img class="portrait" src="https://images.unsplash.com/photo-1519741497674-611481863552?w=1100&q=85&auto=format&fit=crop" alt="Couple in an editorial wedding portrait"><div class="hero-frame"></div><div class="hero-side">Scroll to discover · 2026</div></div><div class="scrollmark">01 / 05 &nbsp; ↓</div></section>
<section class="section shell" id="work"><div class="section-head"><div><div class="kicker">Selected work</div><h2>A visual <em>archive.</em></h2></div><p class="section-intro">A collection of quiet gestures, wild celebrations and everything in between.</p></div><div class="filters"><button class="filter active" data-filter="all">All work</button><button class="filter" data-filter="weddings">Weddings</button><button class="filter" data-filter="portraits">Portraits</button><button class="filter" data-filter="commercial">Commercial</button><button class="filter" data-filter="editorial">Editorial</button></div><div class="gallery" id="gallery"></div></section>
<section class="section about" id="about"><div class="shell about-grid"><img class="about-photo reveal" src="https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=900&q=85&auto=format&fit=crop" alt="Photographer holding a camera"><div class="about-copy"><div class="kicker">The artist</div><p>“The best photographs feel like a memory you didn’t know you had.”</p><div class="body">LENS & LIGHT is a small, thoughtful studio for people who want more than a record of what happened. We look for the in-between: the hand squeeze, the last light, the laugh that wasn’t planned.</div><div class="signature">Alya Rahman</div></div></div></section>
<section class="section shell" id="services"><div class="services"><div><div class="kicker">Ways to work together</div><h2>Made for your <em>chapter.</em></h2><p class="section-intro" style="margin-top:25px">Every session is shaped around you. Tell us what matters and we’ll take care of the rest.</p></div><div class="service-list"><div class="service open"><button class="service-toggle">Weddings & celebrations <span>+</span></button><div class="service-detail">Full-day storytelling, intimate ceremonies and the beautiful chaos in between. From RM 3,800.</div></div><div class="service"><button class="service-toggle">Portraits & personal work <span>+</span></button><div class="service-detail">A relaxed, guided portrait session for individuals, couples and families. From RM 650.</div></div><div class="service"><button class="service-toggle">Commercial & editorial <span>+</span></button><div class="service-detail">Visual direction and image-making for brands, campaigns and publications. Custom quote.</div></div></div></div></section>
<section class="section contact"><div class="shell contact-grid"><div><div class="kicker">Start a conversation</div><h2>Let's make something <em>real.</em></h2><p class="section-intro">Have a date in mind? We’d love to hear what you’re planning.</p></div><form class="contact-form" action="{{ route('bookings.create') }}"><input name="name" placeholder="Your name" required><input name="email" type="email" placeholder="Email address" required><textarea name="message" placeholder="Tell us a little about your story"></textarea><button class="button" type="submit">Check availability ↗</button></form></div></section>
</main><footer class="contact"><div class="shell footer"><span>© 2026 LENS & LIGHT / fotographer</span><span>Kuala Lumpur · hello@lensandlight.studio</span></div></footer>
<div class="lightbox" id="lightbox"><button class="lightbox-close">×</button><button class="lightbox-prev">‹</button><img id="lightbox-image" alt=""><button class="lightbox-next">›</button><div class="lightbox-label" id="lightbox-label"></div></div>
<div class="theme-picker" id="theme-picker"><div class="theme-menu"><button data-theme="system">◐ System</button><button data-theme="light">☼ Light</button><button data-theme="dark">☾ Dark</button></div><button id="theme-toggle" aria-label="Change theme">◐ Theme</button></div>
<script>
const storedTheme=localStorage.getItem('fotographer-theme')||'system';if(storedTheme!=='system')document.documentElement.setAttribute('data-fotographer-theme',storedTheme);const themePicker=document.getElementById('theme-picker');document.getElementById('theme-toggle').onclick=()=>themePicker.classList.toggle('open');document.querySelectorAll('.theme-menu button').forEach(btn=>btn.onclick=()=>{const theme=btn.dataset.theme;localStorage.setItem('fotographer-theme',theme);if(theme==='system')document.documentElement.removeAttribute('data-fotographer-theme');else document.documentElement.setAttribute('data-fotographer-theme',theme);themePicker.classList.remove('open')});
const photos=[
 {title:'After the rain',cat:'weddings',url:'https://images.unsplash.com/photo-1519741497674-611481863552?w=1000&q=85&auto=format&fit=crop',alt:'Wedding couple'},
 {title:'Soft focus',cat:'portraits',url:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900&q=85&auto=format&fit=crop',alt:'Portrait in soft light'},
 {title:'Still / life',cat:'editorial',url:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=1000&q=85&auto=format&fit=crop',alt:'Editorial still life'},
 {title:'Salt air',cat:'weddings',url:'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1000&q=85&auto=format&fit=crop',alt:'Wedding by the sea'},
 {title:'The new classic',cat:'commercial',url:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=900&q=85&auto=format&fit=crop',alt:'Fashion editorial'},
 {title:'Golden hour',cat:'portraits',url:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1000&q=85&auto=format&fit=crop',alt:'Portrait in golden light'},
 {title:'Quiet details',cat:'editorial',url:'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&q=85&auto=format&fit=crop',alt:'Editorial desk'},
 {title:'In the wild',cat:'commercial',url:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1000&q=85&auto=format&fit=crop',alt:'Landscape campaign'}
];
const gallery=document.getElementById('gallery');let activePhotos=photos,current=0;function render(filter='all'){activePhotos=filter==='all'?photos:photos.filter(p=>p.cat===filter);gallery.innerHTML=activePhotos.map((p,i)=>`<figure class="gallery-item" data-index="${i}"><img loading="lazy" src="${p.url}" alt="${p.alt}"><figcaption><b>${p.title}</b><span>${p.cat}</span></figcaption></figure>`).join('');gallery.querySelectorAll('.gallery-item').forEach(el=>el.onclick=()=>openLightbox(+el.dataset.index));}
render();document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});
const lightbox=document.getElementById('lightbox'),lightImg=document.getElementById('lightbox-image'),label=document.getElementById('lightbox-label');function openLightbox(i){current=i;const p=activePhotos[i];lightImg.src=p.url;lightImg.alt=p.alt;label.textContent=p.title+' · '+p.cat;lightbox.classList.add('open')}function move(n){current=(current+n+activePhotos.length)%activePhotos.length;openLightbox(current)}document.querySelector('.lightbox-close').onclick=()=>lightbox.classList.remove('open');document.querySelector('.lightbox-prev').onclick=()=>move(-1);document.querySelector('.lightbox-next').onclick=()=>move(1);lightbox.onclick=e=>{if(e.target===lightbox)lightbox.classList.remove('open')};addEventListener('keydown',e=>{if(e.key==='Escape')lightbox.classList.remove('open');if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)});
document.querySelectorAll('.service-toggle').forEach(btn=>btn.onclick=()=>btn.parentElement.classList.toggle('open'));const cursor=document.getElementById('cursor');addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});document.querySelectorAll('.gallery-item').forEach(el=>{el.onmouseenter=()=>cursor.classList.add('show');el.onmouseleave=()=>cursor.classList.remove('show')});
</script></body></html>
