@extends('public.layouts.brand')

@section('title', 'CoreMemory — Garden Romance')
@section('description', 'Mockup Garden Romance untuk majlis Raja Sehari CoreMemory.')

@section('content')
    <section id="home" class="relative min-h-[720px] scroll-mt-20 overflow-hidden bg-[#f6f0e8] pt-24 text-[#4a3b31] md:min-h-[820px]">
        <div class="absolute inset-0 opacity-40 [background:radial-gradient(circle_at_10%_8%,#d8abb5,transparent_26%),radial-gradient(circle_at_88%_82%,#b8c7a3,transparent_32%)]"></div>
        <div class="relative mx-auto grid max-w-6xl gap-8 px-4 pb-16 pt-14 lg:grid-cols-[.75fr_1.25fr] lg:items-center lg:pt-20">
            <div class="relative z-10" data-reveal><p class="text-xs font-semibold uppercase tracking-[.32em] text-[#a36b70]">CoreMemory · Garden romance</p><h1 class="font-display mt-5 text-6xl leading-[.9] tracking-tight sm:text-7xl lg:text-8xl">Mekar dalam<br><em class="font-normal text-[#a36b70]">cinta.</em></h1><p class="mt-6 max-w-sm leading-8 text-[#78675c]">Sebuah kisah Raja Sehari dalam palet lembut, bunga segar dan cahaya petang yang romantis.</p><a href="#rsvp" class="mt-8 inline-block rounded-full bg-[#8f5e62] px-6 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5">RSVP Majlis ↗</a><div class="mt-11 border-l border-[#b68f87] pl-4 text-xs uppercase tracking-[.17em] text-[#876f61]">20 Disember 2026<br><span class="mt-2 block normal-case tracking-normal">The Glasshouse, Shah Alam</span></div></div>
            <div class="relative h-[480px] sm:h-[600px]" data-reveal><img class="absolute right-0 h-[92%] w-[78%] rounded-t-full object-cover shadow-2xl" src="https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85" alt="Pengantin di taman"><img class="absolute bottom-0 left-0 h-[42%] w-[42%] rounded-[2rem] border-8 border-[#f6f0e8] object-cover" src="https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=700&q=85" alt="Bunga perkahwinan"><div class="absolute right-[4%] top-[9%] grid h-24 w-24 place-items-center rounded-full border border-white/80 bg-[#f9e9dc]/85 text-center font-display text-lg text-[#8f5e62] backdrop-blur">A<br><span class="text-xs">&amp;</span><br>F</div></div>
        </div>
    </section>
    <section class="bg-[#fffdf9] py-20 text-[#4a3b31] md:py-28"><div class="mx-auto max-w-5xl px-4"><div class="grid gap-12 md:grid-cols-2 md:items-center"><div data-reveal><p class="text-xs font-semibold uppercase tracking-[.28em] text-[#a36b70]">The promise</p><h2 class="font-display mt-4 text-5xl tracking-tight">Dua jiwa,<br><em class="font-normal text-[#a36b70]">satu taman.</em></h2></div><p class="leading-8 text-[#78675c]" data-reveal>Jemput hadir meraikan ikatan suci antara Aisyah dan Faris. Bersama kita cipta memori indah dalam suasana garden party yang intim dan penuh kehangatan.</p></div><div class="mt-16 grid gap-6 md:grid-cols-3"><article class="rounded-3xl bg-[#f7ece6] p-7" data-reveal><p class="text-xs uppercase tracking-[.17em] text-[#a36b70]">10:30 pagi</p><h3 class="font-display mt-3 text-3xl">Akad Nikah</h3><p class="mt-3 text-sm leading-6 text-[#78675c]">Majlis di Garden Pavilion.</p></article><article class="rounded-3xl bg-[#edf0e2] p-7" data-reveal><p class="text-xs uppercase tracking-[.17em] text-[#7b8b63]">12:30 tengah hari</p><h3 class="font-display mt-3 text-3xl">Jamuan</h3><p class="mt-3 text-sm leading-6 text-[#78675c]">Makan beradab dan bersua.</p></article><article class="rounded-3xl bg-[#f5eddc] p-7" data-reveal><p class="text-xs uppercase tracking-[.17em] text-[#a48756]">01:00 petang</p><h3 class="font-display mt-3 text-3xl">Bersanding</h3><p class="mt-3 text-sm leading-6 text-[#78675c]">Raikan pasangan di pelamin.</p></article></div></div></section>
    <section class="bg-[#f4e8dd] py-20 text-[#4a3b31] md:py-28"><div class="mx-auto max-w-6xl px-4"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-end" data-reveal><div><p class="text-xs font-semibold uppercase tracking-[.28em] text-[#a36b70]">Little moments</p><h2 class="font-display mt-3 text-5xl">Dari setiap <em class="font-normal text-[#a36b70]">sudut.</em></h2></div><p class="max-w-xs leading-7 text-[#78675c]">Scroll perlahan untuk melihat rasa lembut dan hangat dalam setiap bingkai.</p></div><div class="mt-12 grid gap-4 md:grid-cols-12"><img class="h-80 w-full rounded-[2rem] object-cover md:col-span-5" data-reveal src="{{ asset('images/corememory/malay-wedding-detail.webp') }}" alt="Detail henna dan bunga pengantin"><img class="h-80 w-full rounded-[2rem] object-cover md:col-span-7" data-reveal src="{{ asset('images/corememory/malay-wedding-reception.webp') }}" alt="Momen resepsi Melayu"><img class="h-96 w-full rounded-[2rem] object-cover md:col-span-12" data-reveal src="{{ asset('images/corememory/malay-wedding-portrait.webp') }}" alt="Pasangan pengantin Melayu"></div></div></section>
    <section id="rsvp" class="bg-[#6b454a] py-20 text-[#fff9f3]"><div class="mx-auto max-w-xl px-4 text-center" data-reveal><p class="text-xs font-semibold uppercase tracking-[.3em] text-[#e6b9b2]">RSVP</p><h2 class="font-display mt-4 text-5xl">Seindah bunga,<br><em class="font-normal text-[#ecc9b5]">hadirnya anda.</em></h2><form class="mt-8 rounded-3xl border border-white/25 bg-white/10 p-6 text-left backdrop-blur"><input class="w-full rounded-xl border border-white/25 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/60" placeholder="Nama penuh"><select class="mt-3 w-full rounded-xl border border-white/25 bg-[#80585d] px-4 py-3 text-white"><option>Hadir, insya-Allah</option><option>Tidak dapat hadir</option></select><button type="button" class="mt-5 rounded-full bg-[#fff9f3] px-5 py-3 text-sm font-semibold text-[#6b454a]">Hantar RSVP</button></form></div></section>
    @include('public.partials.design-switcher')
@endsection
