@extends('public.layouts.brand')

@section('title', 'CoreMemory — Midnight Luxe')
@section('description', 'Mockup Midnight Luxe untuk majlis Raja Sehari CoreMemory.')

@section('content')
    <section class="relative min-h-[760px] overflow-hidden bg-[#120f12] pb-16 pt-28 text-[#f8f0e4] md:pt-36"><div class="absolute inset-0 opacity-60 [background:radial-gradient(circle_at_78%_24%,#6d394d,transparent_24%),radial-gradient(circle_at_45%_100%,#9c763c,transparent_35%)]"></div><div class="relative mx-auto grid max-w-6xl gap-12 px-4 lg:grid-cols-2 lg:items-center"><div data-reveal><p class="text-xs font-semibold uppercase tracking-[.35em] text-[#d6ae75]">CoreMemory · Midnight luxe</p><h1 class="font-display mt-5 text-6xl leading-[.88] tracking-tight sm:text-7xl lg:text-8xl">A night made<br>of <em class="font-normal text-[#d4a866]">gold.</em></h1><p class="mt-7 max-w-md leading-8 text-[#c5b5a7]">Perayaan Raja Sehari dengan elegan moden—cahaya lilin, kontras dramatik, dan kenangan yang berkilau.</p><div class="mt-9 flex gap-3"><a href="#rsvp" class="rounded-full bg-[#d4a866] px-6 py-3 text-sm font-semibold text-[#1a1212] transition hover:bg-[#efd09b]">RSVP sekarang</a><a href="#schedule" class="rounded-full border border-[#d4a866]/50 px-6 py-3 text-sm font-semibold text-[#f8f0e4]">Atur cara</a></div></div><div class="relative h-[460px] lg:h-[570px]" data-reveal><div class="absolute inset-8 rounded-[3rem] border border-[#d4a866]/40"></div><img class="absolute inset-0 h-full w-full rounded-[3rem] object-cover opacity-85 [filter:contrast(1.08)_saturate(.65)]" src="https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=85" alt="Majlis makan malam perkahwinan"><div class="absolute inset-0 rounded-[3rem] bg-gradient-to-t from-[#120f12]/85 via-transparent"></div><div class="absolute bottom-9 left-9"><p class="text-xs uppercase tracking-[.25em] text-[#d6ae75]">20 · 12 · 26</p><p class="mt-2 font-display text-3xl">Aisyah &amp; Faris</p></div></div></div></section>
    <section id="schedule" class="bg-[#1a1516] py-20 text-[#f8f0e4] md:py-28"><div class="mx-auto max-w-5xl px-4"><div class="text-center" data-reveal><p class="text-xs font-semibold uppercase tracking-[.3em] text-[#d6ae75]">Evening itinerary</p><h2 class="font-display mt-4 text-5xl">The <em class="font-normal text-[#d4a866]">celebration.</em></h2></div><div class="mt-14 grid gap-px overflow-hidden rounded-3xl border border-[#d4a866]/25 bg-[#d4a866]/25 md:grid-cols-3"><article class="bg-[#1a1516] p-8" data-reveal><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#d6ae75]">07:30 malam</p><h3 class="font-display mt-4 text-3xl">Ketibaan</h3><p class="mt-3 leading-7 text-[#bcaea4]">Tetamu dialu-alukan dengan minuman dan alunan muzik.</p></article><article class="bg-[#1a1516] p-8" data-reveal><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#d6ae75]">08:30 malam</p><h3 class="font-display mt-4 text-3xl">Bersanding</h3><p class="mt-3 leading-7 text-[#bcaea4]">Kemuncak malam untuk dua hati yang diraikan.</p></article><article class="bg-[#1a1516] p-8" data-reveal><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#d6ae75]">10:30 malam</p><h3 class="font-display mt-4 text-3xl">Restu &amp; doa</h3><p class="mt-3 leading-7 text-[#bcaea4]">Sesi bergambar dan salam bersama pengantin.</p></article></div></div></section>
    <section class="bg-[#0e0b0d] py-20 text-[#f8f0e4] md:py-28"><div class="mx-auto max-w-6xl px-4"><div data-reveal><p class="text-xs font-semibold uppercase tracking-[.3em] text-[#d6ae75]">The frames</p><h2 class="font-display mt-4 text-5xl">Cinematic <em class="font-normal text-[#d4a866]">moments.</em></h2></div><div class="mt-12 grid gap-4 md:grid-cols-2"><figure class="group relative h-[460px] overflow-hidden rounded-3xl" data-reveal><img class="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100" src="{{ asset('images/corememory/malay-wedding-portrait.webp') }}" alt="Potret pengantin Melayu"><figcaption class="absolute bottom-6 left-6 text-xs uppercase tracking-[.2em] text-[#d6ae75]">01 / The portrait</figcaption></figure><figure class="group relative h-[460px] overflow-hidden rounded-3xl" data-reveal><img class="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100" src="{{ asset('images/corememory/malay-wedding-reception.webp') }}" alt="Resepsi Melayu"><figcaption class="absolute bottom-6 left-6 text-xs uppercase tracking-[.2em] text-[#d6ae75]">02 / The celebration</figcaption></figure></div><figure class="group relative mt-4 h-72 overflow-hidden rounded-3xl" data-reveal><img class="h-full w-full object-cover opacity-75 transition duration-700 group-hover:scale-105 group-hover:opacity-100" src="{{ asset('images/corememory/malay-wedding-detail.webp') }}" alt="Detail bunga dan henna"><figcaption class="absolute bottom-6 left-6 text-xs uppercase tracking-[.2em] text-[#d6ae75]">03 / The details</figcaption></figure></div></section>
    <section id="rsvp" class="bg-[#120f12] py-20 text-[#f8f0e4]"><div class="mx-auto grid max-w-4xl gap-8 px-4 md:grid-cols-2 md:items-center"><div data-reveal><p class="text-xs font-semibold uppercase tracking-[.3em] text-[#d6ae75]">RSVP</p><h2 class="font-display mt-4 text-5xl leading-tight">Your presence<br>is <em class="font-normal text-[#d4a866]">golden.</em></h2><p class="mt-5 leading-7 text-[#bcaea4]">Sila sahkan kehadiran anda sebelum 6 Disember 2026.</p></div><form class="rounded-3xl border border-[#d4a866]/30 bg-white/5 p-7 backdrop-blur" data-reveal><input class="w-full border-b border-[#d4a866]/30 bg-transparent px-1 py-3 text-[#f8f0e4] outline-none placeholder:text-[#bcaea4]" placeholder="Nama penuh"><input class="mt-4 w-full border-b border-[#d4a866]/30 bg-transparent px-1 py-3 text-[#f8f0e4] outline-none placeholder:text-[#bcaea4]" placeholder="Bilangan tetamu"><button type="button" class="mt-7 rounded-full bg-[#d4a866] px-5 py-3 text-sm font-semibold text-[#1a1212]">Sahkan RSVP</button></form></div></section>
    @include('public.partials.design-switcher')
@endsection
